export const clothesMockData = [{"type":"Konklux","clothesName":"Kolrabi","designerName":"Guilloneau","commentCount":1,"likeCount":1,"score":1,"purchaseLink":"Alopochen aegyptiacus"},
{"type":"Toughjoyfax","clothesName":"Sausage - Meat","designerName":"O'Corren","commentCount":2,"likeCount":2,"score":2,"purchaseLink":"Connochaetus taurinus"},
{"type":"Flexidy","clothesName":"Cinnamon - Ground","designerName":"Cowern","commentCount":3,"likeCount":3,"score":3,"purchaseLink":"Chloephaga melanoptera"},
{"type":"Keylex","clothesName":"Brandy Cherry - Mcguinness","designerName":"Ducroe","commentCount":4,"likeCount":4,"score":4,"purchaseLink":"Anastomus oscitans"},
{"type":"Cardguard","clothesName":"Irish Cream - Butterscotch","designerName":"Winkett","commentCount":5,"likeCount":5,"score":5,"purchaseLink":"Macropus agilis"},
{"type":"Transcof","clothesName":"Chocolate - Dark Callets","designerName":"Huriche","commentCount":6,"likeCount":6,"score":6,"purchaseLink":"Ceryle rudis"},
{"type":"Mat Lam Tam","clothesName":"Boogies","designerName":"Breslauer","commentCount":7,"likeCount":7,"score":7,"purchaseLink":"Corvus albus"},
{"type":"Flowdesk","clothesName":"Sweet Pea Sprouts","designerName":"Yukhnin","commentCount":8,"likeCount":8,"score":8,"purchaseLink":"Macropus eugenii"},
{"type":"Subin","clothesName":"The Pop Shoppe - Grape","designerName":"Corben","commentCount":9,"likeCount":9,"score":9,"purchaseLink":"Sciurus vulgaris"},
{"type":"Konklux","clothesName":"Melon - Cantaloupe","designerName":"Weaben","commentCount":10,"likeCount":10,"score":10,"purchaseLink":"Oreotragus oreotragus"},
{"type":"Ronstring","clothesName":"Swiss Chard","designerName":"Crosthwaite","commentCount":11,"likeCount":11,"score":11,"purchaseLink":"Ovis ammon"},
{"type":"Tampflex","clothesName":"Butter - Salted, Micro","designerName":"Walthall","commentCount":12,"likeCount":12,"score":12,"purchaseLink":"Helogale undulata"},
{"type":"Lotstring","clothesName":"Broom Handle","designerName":"Quinnet","commentCount":13,"likeCount":13,"score":13,"purchaseLink":"unavailable"},
{"type":"Span","clothesName":"Pail - 15l White, With Handle","designerName":"Hasselby","commentCount":14,"likeCount":14,"score":14,"purchaseLink":"Alligator mississippiensis"},
{"type":"Solarbreeze","clothesName":"Walkers Special Old Whiskey","designerName":"Le Merchant","commentCount":15,"likeCount":15,"score":15,"purchaseLink":"Colaptes campestroides"},
{"type":"Voltsillam","clothesName":"Ketchup - Tomato","designerName":"Coade","commentCount":16,"likeCount":16,"score":16,"purchaseLink":"Echimys chrysurus"},
{"type":"Subin","clothesName":"Bagel - Ched Chs Presliced","designerName":"Purslow","commentCount":17,"likeCount":17,"score":17,"purchaseLink":"Pituophis melanaleucus"},
{"type":"It","clothesName":"Sauce - Gravy, Au Jus, Mix","designerName":"Skelhorn","commentCount":18,"likeCount":18,"score":18,"purchaseLink":"Picoides pubescens"},
{"type":"Y-find","clothesName":"Lemons","designerName":"Bordiss","commentCount":19,"likeCount":19,"score":19,"purchaseLink":"Limosa haemastica"},
{"type":"Duobam","clothesName":"Cheese - Shred Cheddar / Mozza","designerName":"Grzelak","commentCount":20,"likeCount":20,"score":20,"purchaseLink":"Uraeginthus angolensis"},
{"type":"Keylex","clothesName":"Teriyaki Sauce","designerName":"Mathewson","commentCount":21,"likeCount":21,"score":21,"purchaseLink":"Dicrurus adsimilis"},
{"type":"Redhold","clothesName":"Tea - Herbal Sweet Dreams","designerName":"Francklyn","commentCount":22,"likeCount":22,"score":22,"purchaseLink":"Haliaetus vocifer"},
{"type":"Domainer","clothesName":"Bag - Regular Kraft 20 Lb","designerName":"Willacot","commentCount":23,"likeCount":23,"score":23,"purchaseLink":"Pycnonotus barbatus"},
{"type":"Otcom","clothesName":"Sauce - Oyster","designerName":"Kender","commentCount":24,"likeCount":24,"score":24,"purchaseLink":"Coendou prehensilis"},
{"type":"Voltsillam","clothesName":"Extract - Raspberry","designerName":"Gillies","commentCount":25,"likeCount":25,"score":25,"purchaseLink":"Didelphis virginiana"},
{"type":"Bamity","clothesName":"Trueblue - Blueberry","designerName":"Ettritch","commentCount":26,"likeCount":26,"score":26,"purchaseLink":"Anser anser"},
{"type":"Pannier","clothesName":"Beef - Eye Of Round","designerName":"Gerhartz","commentCount":27,"likeCount":27,"score":27,"purchaseLink":"Coluber constrictor"},
{"type":"Tresom","clothesName":"Cocoa Powder - Dutched","designerName":"O'Mohun","commentCount":28,"likeCount":28,"score":28,"purchaseLink":"Boa constrictor mexicana"},
{"type":"Ronstring","clothesName":"Bay Leaf","designerName":"Della Scala","commentCount":29,"likeCount":29,"score":29,"purchaseLink":"Corythornis cristata"},
{"type":"Holdlamis","clothesName":"Bread - French Stick","designerName":"Studdard","commentCount":30,"likeCount":30,"score":30,"purchaseLink":"Macropus fuliginosus"},
{"type":"Lotstring","clothesName":"Skirt - 29 Foot","designerName":"Sheryn","commentCount":31,"likeCount":31,"score":31,"purchaseLink":"Pseudoleistes virescens"}];